### ISSUE TITLE
Missing .babelrc file...

### ISSUE THREAD

**Issue by nimoos** [stefanvanherwijnen/quasar-auth-starter#1]
when I run quasar dev 
I'm facing with this error 
Missing .babelrc file...
how can I fix this? 
thanks

**Comment by stefanvanherwijnen** [comment]
Make sure you use Quasar CLI v1. If I remember correctly, .babelrc is changed to babel.config.js in v1.

**Comment by bparker667** [comment]
Quick question @stefanvanherwijnen, if I upgrade to quasar-cli v1, will I still be able to build projects with the old .babelrc file? I am hesitant to upgrade and then have my v0.17 projects to become un-buildable.
Thanks.

**Comment by stefanvanherwijnen** [comment]
Yes, the CLI should be fully backwards compatible.

**Comment by bparker667** [comment]
@stefanvanherwijnen thank you. I have tested and found that it is backwards compatible.
