### ISSUE TITLE
Missing .babelrc file...

### ISSUE THREAD

**Issue by ryan3216** [stefanvanherwijnen/quasar-auth-starter#4]
I have followed official guide. 
http://www.quasarchs.com/guide/quasar-cli.html

Use command "npm install -g quasar-cli" to install quasar,  but the version of quasar  is still v0.17.
Please help.

**Comment by stefanvanherwijnen** [comment]
Try reinstalling everything. It should work so I honestly don't know what's wrong. It might also have been a breaking change in Quasar, but this starter will be ported to an app extension so I am not updating this.

**Comment by ryan3216** [comment]
This issue have already been solved.  The followed page is correct : https://quasar.dev/quasar-cli/installation
